# 将此文件复制为 config.yaml 并填写实际配置
database:
  host: "localhost"           # 数据库服务器地址
  user: "your_db_user"        # 数据库用户名
  password: "your_db_password" # 数据库密码
  name: "your_database_name"  # 数据库名称
  port: 3306                  # MySQL默认端口3306

api:
  key: "your_amap_api_key"    # 高德地图API密钥
  city: "北京"                # 要查询的城市名称（中文）

update:
  update_interval: 3600       # 数据更新间隔(秒)